swagger: '2.0'
info:
  description: "This is study restaurant project"
  version: 1.0.0
  title: Swagger Restaurant
tags:
  - name: categories
    description: Сombines dishes into groups. Classifies dishes
  - name: dishes
    description: Information about dishes. One dish can belong to only one category.
  - name: roles
    description: List of all possible roles for users.
  - name: users
    description: Full information about users.
  - name: orders
    description: It contains full information about the order - dishes, their quantity, cost, date of opening, closing and status.
  - name: login
    description: Login functionality
  - name: logout
    description: Logout functionality

securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
    description: 'Enter your token in the "Bearer {token}" format'
schemes:
  - http
paths:
  /categories:
    get:
      tags:
        - categories
      summary: View all. Sorting and searching
      description: View all categories. Sorting and searching by title 
      security:
      - bearerAuth: []
      parameters:
        - name: sort 
          in: query
          description: Сolumn header for sorting. Must be in the table
          required: false
          type: string
          enum:
            - title
        - name: sort_order
          in: query
          description: Choosing the sorting direction - asc or desc
          required: false
          type: string
          enum:
            - asc
            - desc
        - name: search
          in: query
          description: The column to search for. Must be present in the table
          required: false
          type: string
          enum:
            - title
        - name: search_order
          in: query
          description: The value for the search. Must be in the selected column
          required: false
          type: string
        - name: page
          in: query
          description: Selecting the current page
          required: true
          type: integer
        - name: perPage
          in: query
          description: Select the number of entries per page
          required: true
          type: integer
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/CategoryPaginate'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Category not found
          schema:
            $ref: '#/definitions/ApiResponse'
    post:
      tags:
        - categories
      summary: Create a category 
      description: Create a category. All fields are required
      security:
      - bearerAuth: []
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: title
          description: Title of the category. It must be a unique value in the table
          in: formData
          required: true
          type: string
        - name: file
          description: Image category
          in: formData
          required: true
          type: file
      responses:
        '201':
          description: Successful operation
          schema:
            $ref: '#/definitions/Category'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Category not found
          schema:
            $ref: '#/definitions/ApiResponse'

  /categories/{category}:
    get:
      tags:
        - categories
      summary: View of one category
      description: View of one category by id
      security:
      - bearerAuth: []
      parameters:
        - name: category 
          in: path
          description: Id of the category to search for
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Category'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Category not found
          schema:
            $ref: '#/definitions/ApiResponse'
    delete:
      tags:
        - categories
      summary: Delete one category
      description: Delete one category by id
      security:
      - bearerAuth: []
      parameters:
        - name: category 
          in: path
          description: Id of the category to delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Category'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Category not found
          schema:
            $ref: '#/definitions/ApiResponse'
    post:
      tags:
        - categories
      summary: Category update
      description: Updating the category. You can update as many fields as you want. When updating an image, the old one is deleted.
      security:
      - bearerAuth: []
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: category 
          in: path
          description: Id of the category to update
          required: true
          type: integer
          format: int64
        - name: title
          in: formData
          description: Title of the category. It must be a unique value in the table
          required: false
          type: string
        - name: file
          in: formData
          description: Image category
          required: false
          type: file
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Category'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Category not found
          schema:
            $ref: '#/definitions/ApiResponse'

  /dishes:
    get:
      tags:
        - dishes
      summary: View all. Sorting and searching
      description: View all dishes. Sorting by title, compound, price or calories and searching by title or compound
      security:
      - bearerAuth: []
      parameters:
        - name: sort 
          in: query
          description:  Сolumn header for sorting. Must be in the table
          required: false
          type: string
          enum:
            - title
            - compound
            - price
            - calories
        - name: sort_order
          in: query
          description: Choosing the sorting direction - asc or desc
          required: false
          type: string
          enum:
            - asc
            - desc
        - name: search
          in: query
          description: The column to search for. Must be present in the table
          required: false
          type: string
          enum:
            - compound
            - title
        - name: search_order
          in: query
          description: The value for the search. Must be in the selected column
          required: false
          type: string
        - name: page
          in: query
          description: Selecting the current page
          required: true
          type: integer
        - name: perPage
          in: query
          description: Select the number of entries per page
          required: true
          type: integer
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/DishPaginate'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Category not found
          schema:
            $ref: '#/definitions/ApiResponse'
    post:
      tags:
        - dishes
      summary: Create a dish 
      description: Create a dish. All fields are required
      security:
      - bearerAuth: []
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: title
          description: Title of the dish. It must be a unique value in the table
          in: formData
          required: true
          type: string
        - name: file
          in: formData
          description: Image dish
          required: true
          type: file
        - name: compound
          in: formData
          description: Сomposition of the dish
          required: true
          type: string
        - name: calories
          in: formData
          description: Amount of calories
          required: true
          type: number
        - name: price
          in: formData
          description: The price of the dish
          required: true
          type: number
        - name: category_id
          in: formData
          description: The dish category id
          required: true
          type: integer
          format: int64
      responses:
        '201':
          description: Successful operation
          schema:
            $ref: '#/definitions/Dish'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Dish not found
          schema:
            $ref: '#/definitions/ApiResponse'
  
  /dishes/{id}:
    get:
      tags:
        - dishes
      summary: View of one dish
      description: View of one dish by id
      security:
      - bearerAuth: []
      parameters:
        - name: id 
          in: path
          description: Id of the dish to search for
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Dish'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Dish not found
          schema:
            $ref: '#/definitions/ApiResponse'
    delete:
      tags:
        - dishes
      summary: Delete one dish
      description: Delete one dish by id
      security:
      - bearerAuth: []
      parameters:
        - name: id 
          in: path
          description: Id of the dish to delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Dish'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Dish not found
          schema:
            $ref: '#/definitions/ApiResponse'
    post:
      tags:
        - dishes
      summary: Dish update
      description: Updating the dish. You can update as many fields as you want. When updating an image, the old one is deleted.
      security:
      - bearerAuth: []
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: id 
          in: path
          description: Id of the dish to update
          required: true
          type: integer
          format: int64
        - name: title
          in: formData
          description: Title of the dish. It must be a unique value in the table
          required: false
          type: string
        - name: file
          in: formData
          description: Image dish
          required: false
          type: file
        - name: compound
          in: formData
          description: Сomposition of the dish
          required: false
          type: string
        - name: calories
          in: formData
          description: Amount of calories
          required: false
          type: number
        - name: price
          in: formData
          description: The price of the dish
          required: false
          type: number
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Dish'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Dish not found
          schema:
            $ref: '#/definitions/ApiResponse'

  /roles:
    get:
      tags:
        - roles
      summary: View all roles
      description: View all roles
      security:
      - bearerAuth: []
      parameters:
        - name: page
          in: query
          description: Selecting the current page
          required: true
          type: integer
        - name: perPage
          in: query
          description: Select the number of entries per page
          required: true
          type: integer
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/RolePaginate'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Role not found
          schema:
            $ref: '#/definitions/ApiResponse'
    post:
      tags:
        - roles
      summary: Create a role 
      description: Create a role. All fields are required
      security:
      - bearerAuth: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              name:
                description: The name of the role. Must be a unique value in the table.
                type: string
      responses:
        '201':
          description: Successful operation
          schema:
            $ref: '#/definitions/Role'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Role not found
          schema:
            $ref: '#/definitions/ApiResponse'

  /roles/{id}:
    get:
      tags:
        - roles
      summary: View of one role
      description: View of one role by id
      security:
      - bearerAuth: []
      parameters:
        - name: id 
          in: path
          description: Id of the role to search for
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Role'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Role not found
          schema:
            $ref: '#/definitions/ApiResponse'
    delete:
      tags:
        - roles
      summary: Delete one role
      description: Id of the role to delete
      security:
      - bearerAuth: []
      parameters:
        - name: id 
          in: path
          description: Id of the role to delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Role'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Role not found
          schema:
            $ref: '#/definitions/ApiResponse'
    put:
      tags:
        - roles
      summary: Role update
      description: Updating the role.
      security:
      - bearerAuth: []
      parameters:
        - name: id 
          in: path
          description: Id of the role to update
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          required: false
          schema:
            type: object
            properties:
              name:
                description: The name of the role. Must be a unique value in the table.
                type: string
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Role'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Category not found
          schema:
            $ref: '#/definitions/ApiResponse'

  /users:
    get:
      tags:
        - users
      summary: View all users
      description: View all users. Sorting by name or role_id and searching by name, email or role_id
      security:
      - bearerAuth: []
      parameters:
        - name: sort 
          in: query
          description: Сolumn header for sorting. Must be in the table
          required: false
          type: string
          enum:
            - name
            - role_id
        - name: sort_order
          in: query
          description: Choosing the sorting direction - asc or desc
          required: false
          type: string
          enum:
            - asc
            - desc
        - name: search
          in: query
          description: The column to search for. Must be present in the table
          required: false
          type: string
          enum:
            - name
            - email
            - role_id
        - name: search_order
          in: query
          description: The value for the search. Must be in the selected column
          required: false
          type: string
        - name: page
          in: query
          description: Selecting the current page
          required: true
          type: integer
        - name: perPage
          in: query
          description: Select the number of entries per page
          required: false
          type: integer
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/UserPaginate'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: User not found
          schema:
            $ref: '#/definitions/ApiResponse'
    post:
      tags:
        - users
      summary: Create a user
      description: Create a user. All fields are required
      security:
      - bearerAuth: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              name:
                description: User name
                type: string
              role_id:
                description: Role ID
                type: integer
              email:
                description: The value of the email field must be unique
                type: string
              password:
                description: User password
                type: string
              pincode:
                description: The pincode must consist of 4 digits and be unique
                type: integer
      responses:
        '201':
          description: Successful operation
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: User not found
          schema:
            $ref: '#/definitions/ApiResponse'

  /users/{id}:
    get:
      tags:
        - users
      summary: View of one user
      description:  View of one user by id
      security:
      - bearerAuth: []
      parameters:
        - name: id 
          in: path
          description: Id of the user to search for
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: User not found
          schema:
            $ref: '#/definitions/ApiResponse'
    delete:
      tags:
        - users
      summary: Delete one user
      description: Delete one user by id
      security:
      - bearerAuth: []
      parameters:
        - name: id 
          in: path
          description: Id of the user to delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: User not found
          schema:
            $ref: '#/definitions/ApiResponse'
    put:
      tags:
        - users
      summary: User update
      description: User update
      security:
      - bearerAuth: []
      parameters:
        - name: id 
          in: path
          description: Id of the user to update
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          required: false
          schema:
            type: object
            properties:
              name:
                description: New user name
                type: string
              email:
                description: New user email. The value of the email field must be unique
                type: string
              role_id:
                description: new user role_id
                type: integer
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: User not found
          schema:
            $ref: '#/definitions/ApiResponse'

  /orders:
    get:
      tags:
        - orders
      summary: View all orders
      description: View all orders. Sorting and searching by number, closing_date or user_id.
      security:
      - bearerAuth: []
      parameters:
        - name: sort 
          in: query
          description: Сolumn header for sorting. Must be in the table
          required: false
          type: string
          enum:
            - number
            - closing_date
            - user_id
        - name: sort_order
          in: query
          description: Choosing the sorting direction - asc or desc
          required: false
          type: string
          enum:
            - asc
            - desc
        - name: search
          in: query
          description: The column to search for. Must be present in the table
          required: false
          type: string
          enum:
            - number
            - closing_date
            - user_id
        - name: search_order
          in: query
          description: The value for the search. Must be in the selected column
          required: false
          type: string
        - name: page
          in: query
          description: Selecting the current page
          required: false
          type: integer
        - name: perPage
          in: query
          description: Select the number of entries per page
          required: false
          type: integer
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/OrderPaginate'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Order not found
          schema:
            $ref: '#/definitions/ApiResponse'
    post:
      tags:
        - orders
      summary: Create a order
      description: Create a order. All fields are required
      security:
      - bearerAuth: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              number:
                description: The order number. The minimum length is 3 digits.
                type: string
              user_id:
                description: ID of the user who created the order
                type: integer
              status:
                description: status order
                type: string
                enum:
                  - closed
                  - open
                  - canceled
                  - paid
              dishes:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                      description: Title of the dish
                    quantity:
                      type: integer
                      description: Number of servings
                  required:
                    - title
                    - quantity
      responses:
        '201':
          description: Successful operation
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Order not found
          schema:
            $ref: '#/definitions/ApiResponse'

  /orders/{id}:
    get:
      tags:
        - orders
      summary: View of one order
      description:  View of one order by id
      security:
      - bearerAuth: []
      parameters:
        - name: id 
          in: path
          description: Id of the order to search for
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Order not found
          schema:
            $ref: '#/definitions/ApiResponse'
    delete:
      tags:
        - orders
      summary: Delete one order
      description: Delete one order by id
      security:
      - bearerAuth: []
      parameters:
        - name: id 
          in: path
          description: Id of the order to delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Order not found
          schema:
            $ref: '#/definitions/ApiResponse'
    put:
      tags:
        - orders
      summary: Order update
      description: Order update
      security:
      - bearerAuth: []
      parameters:
        - name: id 
          in: path
          description: Id of the order to update
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          required: false
          schema:
            type: object
            properties:
              creation_date:
                description: Date of creation
                type: string
                format: date-time
              user_id:
                description: User id
                type: integer
              closing_date:
                description: Сlosing date
                type: string
                format: date-time
              status:
                description: Status order
                type: string
                enum:
                  - closed
                  - open
                  - canceled
                  - paid
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Order not found
          schema:
            $ref: '#/definitions/ApiResponse'

  /login:
    post:
      tags:
        - login
      summary: User login
      description: 'Сhecks for the presence of the user with the entered data in the database and returns the access token. Entered data: super admin/admin - email + password/pincode, waiter - pincode only'
      parameters:
        - in: body
          name: body
          required: false
          schema:
            type: object
            properties:
              email:
                description: User email
                type: string
              password:
                description: User password
                type: string
              pincode:
                description: User pincode
                type: integer
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Login'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Login not found
          schema:
            $ref: '#/definitions/ApiResponse'

  /logout:
    post:
      tags:
        - logout
      summary: User logout
      description: Deletes the current user's token
      security:
      - bearerAuth: []
      parameters:
        - in: header
          name: Authorization
          description: Token type and non-hashed token
          required: true
          type: string
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Logout'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Logout not found
          schema:
            $ref: '#/definitions/ApiResponse'

definitions:
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
    example:
      code: 404
      type: Error
      message: Resource not found

  Category:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: ID category
      title:
        type: string
        description: Title category
      file_id:
        type: integer
        description: ID file
      created_at: 
        type: string
        format: date-time
        description: Time of category creation
      updated_at:
        type: string
        format: date-time
        description: Category update time
      deleted_at:
        type: string
        format: date-time
        description: Time to delete a category
    example:
      id: 1
      title: "Drinks"
      file_id: 3
      created_at: "2025-07-04 13:10:21.000"
      updated_at: "2025-07-04 13:10:21.000"
      deleted_at: null

  CategoryPaginate:
    type: object
    properties:
      categories:
        type: array
        items:
          $ref: '#/definitions/Category'
      page:
        description: Current page
        type: integer
      perPage:
        description: Number of entries per page
        type: integer
      total:
        description: Total number of pages
        type: integer
      first_page:
        description: First page URL
        type: string
      last_page:
        description: Last page URL
        type: string
      next_page:
        description: Next page URL
        type: string
      prev_page:
        description: Previous page URL
        type: string

  Dish:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: ID dish
      title:
        type: string
        description: Title dish
      file_id:
        type: integer
        description: ID file
      category_id:
        type: integer
        description: ID category
      calories:
        type: number
        description: Number of calories
      price:
        type: number
        description: The price of the dish
      compound:
        type: string
        description: Сomposition of the dish
      created_at: 
        type: string
        format: date-time
        description: Time of dish creation
      updated_at:
        type: string
        format: date-time
        description: Dish update time
      deleted_at:
        type: string
        format: date-time
        description: Time to delete a dish
    example:
      id: 1
      title: "Сappuccino"
      file_id: 3
      category_id: 1
      calories: 55.2
      price: 150.5
      compound: "Espresso, milk"
      created_at: "2025-07-04 13:10:21.000"
      updated_at: "2025-07-04 13:10:21.000"
      deleted_at: null

  DishPaginate:
    type: object
    properties:
      dishes:
        type: array
        items:
          $ref: '#/definitions/Dish'
      page:
        description: Current page
        type: integer
      perPage:
        description: Number of entries per page
        type: integer
      total:
        description: Total number of pages
        type: integer
      first_page:
        description: First page URL
        type: string
      last_page:
        description: Last page URL
        type: string
      next_page:
        description: Next page URL
        type: string
      prev_page:
        description: Previous page URL
        type: string
  
  Role:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: ID role
      name:
        type: string
        description: name role
      created_at: 
        type: string
        format: date-time
        description: Time of role creation
      updated_at:
        type: string
        format: date-time
        description: Role update time
    example:
      id: 1
      name: "Admin"
      created_at: "2025-07-04 13:10:21.000"
      updated_at: "2025-07-04 13:10:21.000"

  RolePaginate:
    type: object
    properties:
      roles:
        type: array
        items:
          $ref: '#/definitions/Role'
      page:
        description: Current page
        type: integer
      perPage:
        description: Number of entries per page
        type: integer
      total:
        description: Total number of pages
        type: integer
      first_page:
        description: First page URL
        type: string
      last_page:
        description: Last page URL
        type: string
      next_page:
        description: Next page URL
        type: string
      prev_page:
        description: Previous page URL
        type: string

  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: ID user
      name:
        type: string
        description: Name user
      role_id:
        type: integer
        description: ID role
      email:
        type: string
        description: User email
      created_at: 
        type: string
        format: date-time
        description: Time of user creation
      updated_at:
        type: string
        format: date-time
        description: User update time
      deleted_at:
        type: string
        format: date-time
        description: Time to delete a user
    example:
      id: 1
      name: "Anna"
      role_id: 2
      email: "Anna123@gmail.com"
      created_at: "2025-07-04 13:10:21.000"
      updated_at: "2025-07-04 13:10:21.000"
      deleted_at: null

  UserPaginate:
    type: object
    properties:
      users:
        type: array
        items:
          $ref: '#/definitions/User'
      page:
        description: Current page
        type: integer
      perPage:
        description: Number of entries per page
        type: integer
      total:
        description: Total number of pages
        type: integer
      first_page:
        description: First page URL
        type: string
      last_page:
        description: Last page URL
        type: string
      next_page:
        description: Next page URL
        type: string
      prev_page:
        description: Previous page URL
        type: string

  Dish_Order:
    type: object
    properties:
      title:
        type: string
        description: Title dish
      quantity:
        type: integer
        description: quantity of dishes
      price:
        type: number
        description: The price of the dish
      sum:
        type: number
        description: the cost of the dish position

  Order:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: ID order
      number:
        type: string
        description: Order number
      user_id:
        type: integer
        description: ID user
      status:
        type: string
        description: Order status
      creation_date:
        type: string
        format: date-time
        description: Order opening date
      closing_date:
        type: string
        format: date-time
        description: Order closing date
      created_at: 
        type: string
        format: date-time
        description: Time of order creation
      updated_at:
        type: string
        format: date-time
        description: Order update time
      deleted_at:
        type: string
        format: date-time
        description: Time to delete a order
      dishes:
        $ref: '#/definitions/Dish_Order'
    example:
      id: 1
      number: "111--4-686eae2384ce0"
      user_id: 3
      status: "open"
      creation_date: "2025-07-09 18:00:03.000"
      closing_date: null
      created_at: "2025-07-09 18:00:03.000"
      updated_at: "2025-07-09 18:00:03.000"
      deleted_at: null
      dishes:
        title: "Сappuccino"
        quantity: 3
        price: 150.5
        sum: 451.5

  OrderPaginate:
    type: object
    properties:
      orders:
        type: array
        items:
          $ref: '#/definitions/Order'
      page:
        description: Current page
        type: integer
      perPage:
        description: Number of entries per page
        type: integer
      total:
        description: Total number of pages
        type: integer
      first_page:
        description: First page URL
        type: string
      last_page:
        description: Last page URL
        type: string
      next_page:
        description: Next page URL
        type: string
      prev_page:
        description: Previous page URL
        type: string

  Login:
    type: object
    properties:
      access_token:
        type: string
        description: Generated user token
    example:
      access_token: "13|FrgeBJyRvtpgC9Zr37NAaerytrueg0XLFpd4gjSXvKajag4dcda224"

  Logout:
    type: object
    properties:
      message:
        type: string
    example:
      message: "Logged out"
